### ISSUE TITLE
App is crashing on Keon 

### ISSUE THREAD

**Issue by ioana-chiorean** [AlexLakatos/orbit-defender#1]
Install App
Tap to open it 
![2014-04-07-13-30-40](https://cloud.githubusercontent.com/assets/1391451/2630177/4a3d6134-be44-11e3-9f92-5f14c93593c4.png)

**Comment by ioana-chiorean** [comment]
This is a Blocker as the app can not be used.

**Comment by AlexLakatos** [comment]
What's the OS version?

**Comment by ioana-chiorean** [comment]
B2G 1.5.0.0.-prerelease
Git commit: 2014-04-03 00:07:26

**Comment by ioana-chiorean** [comment]
Works fine on Nexus S with B2G 1.1.0.0hd - prerelease

**Comment by ioana-chiorean** [comment]
Works fine on LG Optimus with B2G 1.1.0.0 - prerelease

**Comment by ioana-chiorean** [comment]
Works fine on ZTE Open with B2G 1.5.0.0 - prerelease
Git commit: 2014-04-06 05:37:04

**Comment by ioana-chiorean** [comment]
Works on Keon with Build from April 24th!

**Comment by ioana-chiorean** [comment]
Sorry - it is fixed on 2.0 (renamed old 1.5)
